# default settings: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml

output-reports:
  active: true
  exclude:
    - 'XmlOutputReport'

build:
  maxIssues: 22 # TODO: Remove this setting after adjusting the codebase to Detekt

style:
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
    includeElvis: true
  ClassOrdering:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  MagicNumber:
    excludes: [ "**/test/**" , "**/e2e/**", "**/com/virtuslab/pulumikotlin/scripts/*" ]
  UnusedImports:
    active: true
  UseDataClass:
    active: true
complexity:
  LongMethod:
    excludes: [ "**/test/**" , "**/e2e/**" ]
naming:
  FunctionNaming:
    active: true
    excludes: [ "**/test/**" , "**/e2e/**" ]
performance:
  SpreadOperator:
    active: false
