# default settings: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml

output-reports:
  active: true
  exclude:
    - 'XmlOutputReport'

build:
  maxIssues: 61 # TODO: Remove this setting after adjusting the codebase to Detekt

style:
  MagicNumber:
    excludes: [ "**/test/**" ]
complexity:
  LongMethod:
    excludes: [ "**/test/**" ]
