output-reports:
  active: true
  exclude:
   - 'XmlOutputReport'

build:
  maxIssues: 85 # TODO: Remove this setting after adjusting the codebase to Detekt

style:
  MagicNumber:
    excludes: ["**/test/**"]
