name: Run E2E tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  kubernetes-e2e-test:
    name: Run end-to-end tests of Pulumi Kotlin Kubernetes
    runs-on: self-hosted
    steps:
      - name: Check out project sources
        uses: actions/checkout@v3
      - name: Run Minikube
        run: minikube start --force
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 11
      - name: Set up Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Publish Pulumi Kotlin Kubernetes to Maven Local
        run: ./gradlew publishPulumiKubernetesPublicationToMavenLocal -x formatKotlinPulumiKubernetes -x dokkaPulumiKubernetesJavadoc
      - name: Run E2E tests
        id: run-kubernetes-e2e-tests
        run: ./gradlew e2eTest --tests KubernetesE2eTest
        env:
          # Pulumi personal access token manually added to `pulumi-kotlin` repo by @myhau (Michal Fudala)
          PULUMI_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_PULUMI }}
      - name: Upload E2E test report
        if: ${{ failure() && steps.run-kubernetes-e2e-tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: kubernetes-e2e-test-report
          path: ./build/reports/tests/e2eTest/*
          retention-days: 3
