name:  Test Minikube

on:
  pull_request:

jobs:
  test-minikube:
    name: Test Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Check out project sources
        uses: actions/checkout@v2
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
