name: Publish pulumi-kotlin to Maven Local before release

on:
  pull_request:

jobs:
  publish:
    name: Publish pulumi-kotlin to Maven Local Repository
    runs-on: [ self-hosted, active ]
    strategy:
      fail-fast: false
      matrix:
        provider: [
          cloudflare, slack, github, random, gcp, google-native, aws, aws-native, azure, azure-native, kubernetes,
          nomad, docker, gitlab, digitalocean, alicloud
        ]
    steps:
      - name: Check out project sources
        uses: actions/checkout@v3
      - name: Get branch name
        id: check_branch_name
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          if [[ $branch_name =~ prepare-release.* ]]; then is_release=true; else is_release=false; fi
          echo "is_release=$is_release" >> $GITHUB_OUTPUT
      - name: Publish to Maven Local
        if: ${{ steps.check_branch_name.outputs.is_release == 'true' }}
        run: ./gradlew publishPulumi${{ matrix.provider }}PublicationToMavenLocal -Dorg.gradle.daemon=false -q
