name: Publish pulumi-kotlin to Maven Local

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    name: Publish pulumi-kotlin to Maven Local Repository
    runs-on: [ self-hosted, active ]
    if: ${{ startsWith(github.head_ref, 'test-automated-releases') || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        provider: [
          cloudflare, slack, github, random, gcp, google-native, aws, aws-native, azure, azure-native, kubernetes,
          nomad, docker, gitlab, digitalocean, alicloud
        ]
    steps:
      - name: Check out project sources
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Check if publication to Maven Local is necessary
        id: check-for-release
        shell: python
        run: |
          import os
          import json
          with open("src/main/resources/version-config.json") as version_config:
            schemas = json.load(version_config)
            version = [schema["kotlinVersion"] for schema in schemas if schema["providerName"] == "${{ matrix.provider }}"][0]
            is_release = not version.endswith("-SNAPSHOT")
            with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              fh.write('is_release=' + str(is_release).lower())
      - name: Publish to Maven Local
        run: ./gradlew publishPulumi${{ matrix.provider }}PublicationToMavenLocal -Dorg.gradle.daemon=false -q
        if: |
          ${{ 
            (startsWith(github.head_ref, 'test-automated-releases') && steps.check-for-release.outputs.is_release == 'true') 
            || (github.event_name == 'push' && steps.check-for-release.outputs.is_release == 'false') 
            || github.event_name == 'workflow_dispatch'
          }}
