name: Tag release

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    name: Tag release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Check if release file was changed
        id: changed-files-specific
        uses: tj-actions/changed-files@v33
        with:
          files: src/main/resources/version-config.json
      - name: Tag new versions of Pulumi Kotlin (if available)
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          ./gradlew tagRecentReleases
          git push --tags
