name: Test

on:
  push:
    branches:
      - release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out project sources
        uses: actions/checkout@v2
      - name: Test
        run: echo "Hello world"
